### ISSUE TITLE
Pass Sonar Lint

### ISSUE THREAD

**Issue by jimender2** [ASHLANDACMCLUB/ashlandacmclub.github.io#24]
Best Practice for the website.

https://webhint.io/scanner/fffe7f04-066a-4eeb-8e81-23da9b57810e

Fix the things that are listed as needing to be fixed for greater compatibility and speed.

- [ ] hint #1: <html> element must have a lang attribute

- [ ] hint #2: <ul> and <ol> must only directly contain <li>, <script> or <template> elements

- [ ] hint #1: 'charset' meta element should be the first thing in '<head>'.

- [ ] hint #1: 'viewport' meta element was not specified.

- [ ] hint #1: 'apple-touch-icon' link element was not specified.

- [ ] hint #1: 'https://ashlandacmclub. … /pics/acm_logoBanner.png' could be around 270.32kB (58%) smaller.

- [ ] hint #1: The target should not be cached, or have a small "max-age" value (180): max-age=600

- [ ] hint #2: Static resources should have a long cache value (31536000) and use the immutable directive: max-age=600

- [ ] hint #3: Static resources should have a long cache value (31536000) and use the immutable directive: max-age=600

- [ ] hint #4: Static resources should have a long cache value (31536000) and use the immutable directive: max-age=600

- [ ] hint #5: Static resources should have a long cache value (31536000) and use the immutable directive: max-age=600

- [ ] hint #6: No "cache-control" header or empty value found. It should have a value

- [ ] hint #1: Response should be compressed with Zopfli when gzip compression is requested.

- [ ] hint #2: Response should be compressed with Zopfli when gzip compression is requested.

- [ ] hint #3: Response should be compressed with Brotli when Brotli compression is requested over HTTPS.

- [ ] hint #4: Response should be compressed with Zopfli when gzip compression is requested.

- [ ] hint #5: Response should be compressed with Brotli when Brotli compression is requested over HTTPS.

- [ ] hint #6: Response should be compressed with Brotli when Brotli compression is requested over HTTPS.

- [ ] hint #1: Response should include 'x-content-type-options' header.

- [ ] hint #2: Response should include 'x-content-type-options' header.

- [ ] hint #3: Response should include 'x-content-type-options' header.

- [ ] hint #1: webhint didn't return the result fast enough. Please try later and if the problem continues, contact us.

Mostly take a look at the page and do additional scans after fixing the issues on the page.
